#!/bin/sh
echo "******** Start fixrepo ****************************"
echo "Clean yum meta data"
yum --disablerepo=* --enablerepo=mratwork* clean all >/dev/null

if [ "$(rpm -qa|grep 'mratwork-')" != "" ] ; then
	echo "Update mratwork-release"
	yum update mratwork* -y >/dev/null
fi

. /script/fix-urgent
echo "******** End fixrepo ****************************"