#!/bin/sh

pfile="/usr/local/lxlabs/kloxo/etc/process/mysql"

if [ -f $pfile ] ; then
	rm -f "${pfile}"*
fi

if [ -f /script/custom.restart-list.inc ] ; then
	. /script/custom.restart-list.inc
else
	. /script/restart-list.inc
fi

list=${list_mysql[*]}

if [ -f /script/custom.restart.inc ] ; then
	. /script/custom.restart.inc
else
	. /script/restart.inc
fi
