#!/bin/sh

if [ -f /script/custom.restart-list.inc ] ; then
	. /script/custom.restart-list.inc
else
	. /script/restart-list.inc
fi

if [ "$1" != "" ] ; then
	list=$($1)
else
	list=${list_services[*]}
fi

if [ -f /script/custom.restart.inc ] ; then
	. /script/custom.restart.inc
else
	. /script/restart.inc
fi